[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.11.14", features = ["blocking"]}
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1.0.156", features = ["derive"] }
toml = "0.7.3"
serde_json = "1.0.91"

